Add error step in workflow

diff --git a/.github/workflows/build-homolog.yaml b/.github/workflows/build-homolog.yaml
--- a/.github/workflows/build-homolog.yaml
+++ b/.github/workflows/build-homolog.yaml
@@ -41,6 +41,9 @@ jobs:
     name: Build Homolog
     needs: [ setup ]
     runs-on: ubuntu-latest
+    outputs:
+      error_message: ${{ steps.update-homolog.outputs.error }}
+      wellcome_message: ${{ steps.update-homolog.outputs.welcome }}
     steps:
       - name: Checkout do repositório
         uses: actions/checkout@v2
@@ -48,7 +51,9 @@ jobs:
           fetch-depth: 0
 
       - name: Atualizar branch homolog
+        id: update-homolog
         run: |
+          echo "welcome='Seja bem vindo'" >> $GITHUB_OUTPUT
           git config --global user.email "robot@github.com"
           git config --global user.name "Homolog Robot"
           git fetch --all
@@ -56,8 +61,19 @@ jobs:
           lista_branches=''
           if [[ -f homolog-branches ]]; then
             lista_branches=$(cat homolog-branches)
-          fi;          
-          lista_branches=`echo -e "$lista_branches\n${{ needs.setup.outputs.branches }}" | tr ' ' '\n' | sort -u`                              
+          fi;
+
+          while read -r branch; do
+            set +e
+            git ls-remote --exit-code --heads origin $branch &> /dev/null
+            if [[ "$?" != "0" ]]; then
+              echo "error=Branch não existe: '$branch'" >> $GITHUB_OUTPUT
+              set -e
+              exit 1
+            fi
+          done <<< "${{ needs.setup.outputs.branches }}"
+
+          lista_branches=`echo -e "$lista_branches\n${{ needs.setup.outputs.branches }}" | tr ' ' '\n' | sort -u`
           git checkout develop
           git branch -D homolog
           git checkout -b homolog develop
@@ -70,18 +86,21 @@ jobs:
             branch_exists=$?
             echo "DEBUG: Verificou se $branch $branch_exists"
             branch_merged=0
-            if [ $branch_exists -eq 0 ]; then
+            if [[ "$branch_exists" == "0" ]]; then
               git checkout $branch
               git log --pretty=format:"%h" develop | grep `git log --pretty=format:"%h" -1 $branch` &> /dev/null
               branch_merged=$?
             fi
-            if [ $branch_exists -eq 0 ] && [ $branch_merged -ne 0 ]; then
+            if [[ "$branch_exists" == "0" ]] && [[ "$branch_merged" != "0" ]]; then
               set -e
               git rebase develop
               git checkout homolog
               git merge $branch --no-edit
             else
               set -e
+              if [[ "$branch_exists" != "0" ]]; then
+                echo "DEBUG: Branch $branch não existe!!"
+              fi
               nova_lista="${nova_lista//$branch/}"
             fi
           done <<< "$lista_branches"
@@ -108,6 +127,16 @@ jobs:
             Branches updated: ${{ steps.branches.outputs.values }}
             Automation completed.
 
+  simple-error-report:
+    if: failure() && !cancelled()
+    name: Close Issue
+    needs: [ merge-branch ]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Show report
+        run: |
+          echo "${{ needs.merge-branch.outputs.error_message }}"
+
   close-issue-with-error:
     if: failure() && !cancelled()
     name: Close Issue
@@ -119,6 +148,9 @@ jobs:
         with:
           issue-number: ${{ github.event.issue.number }}
           comment: |
-            ## Error :sob:
-            Automation failed.
-            You can view the error accessing the [action log](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).
+            ## Automation failed. :sob:
+
+            Errors ocurred during automation:
+            - ${{ needs.merge-branch.outputs.error_message }}
+
+            You can view all logs acessing [action log](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).
