add bash script

diff --git a/.github/workflows/build-homolog.yaml b/.github/workflows/build-homolog.yaml
--- a/.github/workflows/build-homolog.yaml
+++ b/.github/workflows/build-homolog.yaml
@@ -53,16 +53,10 @@ jobs:
       - name: Atualizar branch homolog
         id: update-homolog
         run: |
-          echo "welcome='Seja bem vindo'" >> $GITHUB_OUTPUT
+          # Valida lista de entrega de branches
           git config --global user.email "robot@github.com"
           git config --global user.name "Homolog Robot"
-          git fetch --all
-          git checkout homolog
-          lista_branches=''
-          if [[ -f homolog-branches ]]; then
-            lista_branches=$(cat homolog-branches)
-          fi;
-
+          git fetch --all &> /dev/null
           while read -r branch; do
             set +e
             git ls-remote --exit-code --heads origin $branch &> /dev/null
@@ -73,44 +67,20 @@ jobs:
             fi
           done <<< "${{ needs.setup.outputs.branches }}"
 
+          # Mescla lista de entrada com branches de homolog
+          git checkout homolog &> /dev/null
+          lista_branches=''
+          if [[ -f homolog-branches ]]; then
+            lista_branches=$(cat homolog-branches)
+          fi;
           lista_branches=`echo -e "$lista_branches\n${{ needs.setup.outputs.branches }}" | tr ' ' '\n' | sort -u`
-          git checkout develop
-          git branch -D homolog
-          git checkout -b homolog develop
-          nova_lista=$lista_branches
-          echo "DEBUG: Entrando no loop"
-          while read -r branch; do
-            set +e
-            echo "DEBUG: Verifica se $branch existe"
-            git ls-remote --exit-code --heads origin $branch &> /dev/null
-            branch_exists=$?
-            echo "DEBUG: Verificou se $branch $branch_exists"
-            branch_merged=0
-            if [[ "$branch_exists" == "0" ]]; then
-              git checkout $branch
-              git log --pretty=format:"%h" develop | grep `git log --pretty=format:"%h" -1 $branch` &> /dev/null
-              branch_merged=$?
-            fi
-            if [[ "$branch_exists" == "0" ]] && [[ "$branch_merged" != "0" ]]; then
-              set -e
-              git rebase develop
-              git checkout homolog
-              git merge $branch --no-edit
-            else
-              set -e
-              if [[ "$branch_exists" != "0" ]]; then
-                echo "DEBUG: Branch $branch não existe!!"
-              fi
-              nova_lista="${nova_lista//$branch/}"
-            fi
-          done <<< "$lista_branches"
-          echo "Preparando homolog"
-          git checkout homolog
-          echo $nova_lista | tr ' ' '\n' > homolog-branches
-          echo "Atualizando lista"
-          git add .
-          git commit -m "Atualizando homolog com $nova_lista"
-          git push --force origin homolog
+
+          # Processa novo homolog
+          set +e
+          output=`bash .github/support/deploy-environment.sh "$lista_branches"`
+          result=$?
+          echo "error=$output" >> $GITHUB_OUTPUT
+          exit $result
 
   close-issue-with-success:
     if: success() && !cancelled()
@@ -126,16 +96,6 @@ jobs:
             ## Finish :rocket:
             Branches updated: ${{ steps.branches.outputs.values }}
             Automation completed.
-
-  simple-error-report:
-    if: failure() && !cancelled()
-    name: Close Issue
-    needs: [ merge-branch ]
-    runs-on: ubuntu-latest
-    steps:
-      - name: Show report
-        run: |
-          echo "${{ needs.merge-branch.outputs.error_message }}"
 
   close-issue-with-error:
     if: failure() && !cancelled()
